'use strict';

module.exports = {
    countryCodes: [
        'AF',
        'AX',
        'AL',
        'DZ',
        'AS',
        'AD',
        'AO',
        'AI',
        'AQ',
        'AG',
        'AR',
        'AM',
        'AW',
        'AU',
        'AT',
        'AZ',
        'BS',
        'BH',
        'BD',
        'BB',
        'BY',
        'BE',
        'BZ',
        'BJ',
        'BM',
        'BT',
        'BO',
        'BA',
        'BW',
        'BV',
        'BR',
        'IO',
        'BN',
        'BG',
        'BF',
        'BI',
        'KH',
        'CM',
        'CA',
        'CV',
        'KY',
        'CF',
        'TD',
        'CL',
        'CN',
        'CX',
        'CC',
        'CO',
        'KM',
        'CG',
        'CD',
        'CK',
        'CR',
        'CI',
        'HR',
        'CU',
        'CY',
        'CZ',
        'DK',
        'DJ',
        'DM',
        'DO',
        'EC',
        'EG',
        'SV',
        'GQ',
        'ER',
        'EE',
        'ET',
        'FK',
        'FO',
        'FJ',
        'FI',
        'FR',
        'GF',
        'PF',
        'TF',
        'GA',
        'GM',
        'GE',
        'DE',
        'GH',
        'GI',
        'GR',
        'GL',
        'GD',
        'GP',
        'GU',
        'GT',
        'GG',
        'GN',
        'GW',
        'GY',
        'HT',
        'HM',
        'VA',
        'HN',
        'HK',
        'HU',
        'IS',
        'IN',
        'ID',
        'IR',
        'IQ',
        'IE',
        'IM',
        'IL',
        'IT',
        'JM',
        'JP',
        'JE',
        'JO',
        'KZ',
        'KE',
        'KI',
        'KR',
        'KW',
        'KG',
        'LA',
        'LV',
        'LB',
        'LS',
        'LR',
        'LY',
        'LI',
        'LT',
        'LU',
        'MO',
        'MK',
        'MG',
        'MW',
        'MY',
        'MV',
        'ML',
        'MT',
        'MH',
        'MQ',
        'MR',
        'MU',
        'YT',
        'MX',
        'FM',
        'MD',
        'MC',
        'MN',
        'ME',
        'MS',
        'MA',
        'MZ',
        'MM',
        'NA',
        'NR',
        'NP',
        'NL',
        'AN',
        'NC',
        'NZ',
        'NI',
        'NE',
        'NG',
        'NU',
        'NF',
        'MP',
        'NO',
        'OM',
        'PK',
        'PW',
        'PS',
        'PA',
        'PG',
        'PY',
        'PE',
        'PH',
        'PN',
        'PL',
        'PT',
        'PR',
        'QA',
        'RE',
        'RO',
        'RU',
        'RW',
        'BL',
        'SH',
        'KN',
        'LC',
        'MF',
        'PM',
        'VC',
        'WS',
        'SM',
        'ST',
        'SA',
        'SN',
        'RS',
        'SC',
        'SL',
        'SG',
        'SK',
        'SI',
        'SB',
        'SO',
        'ZA',
        'GS',
        'ES',
        'LK',
        'SD',
        'SR',
        'SJ',
        'SZ',
        'SE',
        'CH',
        'SY',
        'TW',
        'TJ',
        'TZ',
        'TH',
        'TL',
        'TG',
        'TK',
        'TO',
        'TT',
        'TN',
        'TR',
        'TM',
        'TC',
        'TV',
        'UG',
        'UA',
        'AE',
        'GB',
        'US',
        'UM',
        'UY',
        'UZ',
        'VU',
        'VE',
        'VN',
        'VG',
        'VI',
        'WF',
        'EH',
        'YE',
        'ZM',
        'ZW'
    ],
    sms: {
        MAIN_ENDPOINT: 'http://api.infobip.com/api/v3/sendsms/json',
        SECONDARY_ENDPOINT: 'http://api2.infobip.com/api/v3/sendsms/json'
    },
    Options: {
        Ton: {
            UNKNOWN: 0,
            INTERNATIONAL: 1,
            NATIONAL: 2,
            NETWORK_SPECIFIC: 3,
            SUBSCRIBER_NUMBER: 4,
            ALPHANUMERIC: 5,
            ABBREVIATED: 6
        },
        Npi: {
            Unknown: 0,
            ISDN: 1,
            DATA: 3,
            TELEX: 4,
            LAND_MOBILE: 6,
            NATIONAL: 8,
            PRIVATE: 9,
            ERMES: 10,
            INTERNET: 14,
            WAP_CLIENT: 18
        }
    },
    errors: {
        "0": {
            status: 'ALL_RECIPIENTS_PROCESSED',
            description: 'Request was successful (all recipients)'
        },
        "-1": {
            status: "SEND_ERROR",
            description: "Error in processing the request"
        },
        "-2": {
            status: 'NOT_ENOUGH_CREDITS',
            description: 'Not enough credits on a specific account'
        },
        "-3": {
            status: 'NETWORK_NOTCOVERED',
            description: 'Targeted network is not covered on specific account'
        },
        "-5": {
            status: 'INVALID_USER_OR_PASS',
            description: 'Username or password is invalid'
        },
        "-6": {
            status: 'MISSING_DESTINATION_ADDRESS',
            description: 'Destination address is missing in the request'
        },
        "-10": {
            status: 'MISSING_USERNAME',
            description: 'Username is missing in the request'
        },
        "-11": {
            status: 'MISSING_PASSWORD',
            description: 'Password is missing in the request'
        },
        "-13": {
            status: 'INVALID_DESTINATION_ADDRESS',
            description: 'Number is not recognized by Infobip platform'
        },
        "-22": {
            status: 'SYNTAX_ERROR',
            description: 'Incorrect JSON format, caused by syntax error'
        },
        "-23": {
            status: 'ERROR_PROCESSING',
            description: 'General error, reasons may vary'
        },
        "-26": {
            status: 'COMMUNICATION_ERROR',
            description: 'General API error, reasons may vary'
        },
        "-27": {
            status: 'INVALID_SENDDATETIME',
            description: 'Invalid scheduling parameter'
        },
        "-28": {
            status: 'INVALID_DELIVERY_REPORT_PUSH_URL',
            description: 'Invalid PushURL in the request'
        },
        "-30": {
            status: 'INVALID_CLIENT_APPID',
            description: 'Invalid APPID in the request'
        },
        "-33": {
            status: 'DUPLICATE_MESSAGEID',
            description: 'Duplicated MessageID in the request'
        },
        "-34": {
            status: 'SENDER_NOT_ALLOWED',
            description: 'Sender name is not allowed'
        },
        "-99": {
            status: 'GENERAL_ERROR',
            description: 'Error in processing request, reasons may vary'
        },
        "1": {
            status: "EC_UNKNOWN_SUBSCRIBER"
        },
        "1027": {
            status: "EC_OR_encapsulatedAC_NotSupported"
        },
        5: {
            status: "EC_UNIDENTIFIED_SUBSCRIBER"
        },
        1028: {
            status: "EC_OR_transportProtectionNotAdequate"
        },
        "6": {
            status: "EC_ABSENT_SUBSCRIBER_SM"
        },
        "1030": {
            status: "EC_OR_potentialVersionIncompatibility"
        },
        "9": {
            status: "EC_ILLEGAL_SUBSCRIBER"
        },
        "1031": {
            status: "EC_OR_remoteNodeNotReachable"
        },
        "11": {
            status: "EC_TELESERVICE_NOT_PROVISIONED"
        }
    }
};
